chore(github): ISSUE-8 adding CI and unit test workflow github action
OPEN-ENT-NG/geogebra pull request #9
Opened 2022-09-15 15:52 UTC by simonchaval

## Describe your changes
Implementation of CI and unit test for geogebra module
## Checklist tests

## Issue ticket number and link
ISSUE-8
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-15 15:58 UTC, sjollois approved these changes

2022-09-16 06:29 UTC, JinDouang requested changes

2022-09-16 06:29 UTC, JinDouang commented on build.gradle
> +    compile "org.apache.commons:commons-text:1.6"
pas besoin, si ?

2022-09-16 06:30 UTC, JinDouang commented on build.gradle
> +    implementation 'junit:junit:4.13.1'
Pourquoi tu n'utilises pas la même version que celui que tu utilises pour testCompile ?

2022-09-16 08:06 UTC, JinDouang approved these changes

2022-09-16 08:16 UTC, merged